// Predefined work phases for EURO EL
// Organized by category for better UX in dropdowns

export const PREDEFINED_PHASES = [
  // BOR01xx - FORATURA PASSAGGI E FISSAGGIO PERNI
  { code: "BOR0101", description: "FORATURA PASSAGGI E FISSAGGIO PERNI LOWER DECK", category: "BOR01" },
  { code: "BOR0102", description: "FORATURA PASSAGGI E FISSAGGIO PERNI BEACH AREA", category: "BOR01" },
  { code: "BOR0103", description: "FORATURA PASSAGGI E FISSAGGIO PERNI MAIN DECK", category: "BOR01" },
  { code: "BOR0104", description: "FORATURA PASSAGGI E FISSAGGIO PERNI UPPER DECK", category: "BOR01" },
  { code: "BOR0105", description: "FORATURA PASSAGGI E FISSAGGIO PERNI BRIDGE DECK", category: "BOR01" },

  // BOR02xx - CHIUSURA PASSAGGI
  { code: "BOR0201", description: "CHIUSURA PASSAGGI LUNGA PERCORRENZA", category: "BOR02" },
  { code: "BOR0202", description: "CHIUSURA PASSAGGI SALA MACCHINE E BEACH AREA", category: "BOR02" },
  { code: "BOR0203", description: "CHIUSURA PASSAGGI STABILIZZATORI", category: "BOR02" },
  { code: "BOR0204", description: "CHIUSURA PASSAGGI PONTE MAIN DECK UPPER DECK E BRIDGE DECK", category: "BOR02" },
  { code: "BOR2102", description: "COLLEGAMENTO QUADRO STACCABATTERIE MOTORI", category: "BOR02" },
  { code: "BOR2202", description: "COLLEGAMENTO QUADRO STACCABATTERIE GENERATORI", category: "BOR02" },

  // BOR03xx - CANALIZZAZIONI
  { code: "BOR0301", description: "CANALIZZAZIONI SALA MACCHINE", category: "BOR03" },
  { code: "BOR0302", description: "CANALIZZAZIONI BEACH AREA", category: "BOR03" },
  { code: "BOR0303", description: "CANALIZZAZIONI PONTE LOWER DECK", category: "BOR03" },
  { code: "BOR0304", description: "CANALIZZAZIONI PONTE MAIN DECK", category: "BOR03" },
  { code: "BOR0305", description: "CANALIZZAZIONI PONTE UPPER DECK", category: "BOR03" },
  { code: "BOR0306", description: "CANALIZZAZIONI PONTE BRIDGE DECK E ALBERO", category: "BOR03" },

  // BOR04xx - STESURA CAVI
  { code: "BOR0402", description: "STESURA CAVI LUNGA PERCORRENZA", category: "BOR04" },
  { code: "BOR0502", description: "STESURA CAVI SALA MACCHINE", category: "BOR04" },

  // BOR05xx - STESURA PONTI INTERNI
  { code: "BOR0503", description: "STESURA PONTI INTERNI SALA MACCHINE", category: "BOR05" },
  { code: "BOR0602", description: "STESURA CAVI GARAGE E INGRESSO LOCALE TECNICO", category: "BOR05" },
  { code: "BOR0603", description: "STESURA PONTI INTERNI GARAGE E INGRESSO LOCALE TECNICO", category: "BOR05" },
  { code: "BOR0702", description: "STESURA CAVI BEACH AREA E LOCALE TECNICO POPPA", category: "BOR05" },
  { code: "BOR0802", description: "STESURA CAVI VIP LOBBY SCALE E SENTINA LOWER DECK", category: "BOR05" },
  { code: "BOR0803", description: "STESURA PONTI INTERNI VIP LOBBY SCALE E SENTINA LOWER DECK", category: "BOR05" },

  // BOR06xx - STESURA PONTI INTERNI SALA MACCHINE
  { code: "BOR0503", description: "STESURA PONTI INTERNI SALA MACCHINE", category: "BOR06" },
  { code: "BOR0602", description: "STESURA CAVI GARAGE E INGRESSO LOCALE TECNICO", category: "BOR06" },
  { code: "BOR0603", description: "STESURA PONTI INTERNI GARAGE E INGRESSO LOCALE TECNICO", category: "BOR06" },
  { code: "BOR0702", description: "STESURA CAVI BEACH AREA E LOCALE TECNICO POPPA", category: "BOR06" },
  { code: "BOR0802", description: "STESURA CAVI VIP LOBBY SCALE E SENTINA LOWER DECK", category: "BOR06" },
  { code: "BOR0803", description: "STESURA PONTI INTERNI VIP LOBBY SCALE E SENTINA LOWER DECK", category: "BOR06" },

  // BOR23 - COLLEGAMENTO APPARATI SALA MACCHINE
  { code: "BOR23", description: "COLLEGAMENTO APPARATI SALA MACCHINE", category: "BOR23" },

  // BOR24 - INTESTAZIONE CAVI QUADRO BEACH AREA
  { code: "BOR2401", description: "INTESTAZIONE CAVI QUADRO BEACH AREA", category: "BOR24" },
  { code: "BOR2403", description: "COLLEGAMENTO QUADRO BEACH AREA", category: "BOR24" },

  // BOR25 - COLLEGAMENTO QUADRO PRESA DA TERRA
  { code: "BOR2502", description: "COLLEGAMENTO QUADRO PRESA DA TERRA", category: "BOR25" },

  // BOR26 - COLLEGAMENTO QUADRO INTERRUTTORE PRESA DA TERRA
  { code: "BOR26", description: "COLLEGAMENTO QUADRO INTERRUTTORE PRESA DA TERRA", category: "BOR26" },

  // BOR27 - COLLEGAMENTO TRASFORMATORE DI ISOLAMENTO
  { code: "BOR27", description: "COLLEGAMENTO TRASFORMATORE DI ISOLAMENTO", category: "BOR27" },

  // BOR28 - COLLEGAMENTO STACCABATTERIE SERVIZI
  { code: "BOR2802", description: "COLLEGAMENTO STACCABATTERIE SERVIZI", category: "BOR28" },

  // BOR29 - COLLEGAMENTO STACCABATTERIE MOTOPOMPA
  { code: "BOR2902", description: "COLLEGAMENTO STACCABATTERIE MOTOPOMPA", category: "BOR29" },

  // BOR30 - COLLEGAMENTO STACCABATTERIE TIMONI
  { code: "BOR3002", description: "COLLEGAMENTO STACCABATTERIE TIMONI", category: "BOR30" },

  // BOR31 - COLLEGAMENTO ESTRATTORE E.10
  { code: "BOR3102", description: "COLLEGAMENTO ESTRATTORE E.10", category: "BOR31" },

  // BOR32 - COLLEGAMENTO APPARATI LOCALE TECNICO POPPA
  { code: "BOR32", description: "COLLEGAMENTO APPARATI LOCALE TECNICO POPPA", category: "BOR32" },

  // BOR33 - COLLEGAMENTO APPARATI BEACH
  { code: "BOR33", description: "COLLEGAMENTO APPARATI BEACH", category: "BOR33" },

  // BOR34 - INTESTAZIONE CAVI QUADRO OSPITI E VIP LOWER DECK
  { code: "BOR3401", description: "INTESTAZIONE CAVI QUADRO OSPITI E VIP LOWER DECK", category: "BOR34" },
  { code: "BOR3403", description: "COLLEGAMENTO QUADRO OSPITI E VIP LOWER DECK", category: "BOR34" },

  // BOR35 - COLLEGAMENTO APPARATI OSPITI E VIP LOWER DECK
  { code: "BOR35", description: "COLLEGAMENTO APPARATI OSPITI E VIP LOWER DECK", category: "BOR35" },

  // BOR36 - COLLEGAMENTO SENTINA LOWER DECK POPPA
  { code: "BOR36", description: "COLLEGAMENTO SENTINA LOWER DECK POPPA", category: "BOR36" },

  // BOR37 - COLLEGAMENTO APPARATI SENTINA ZONA CUCINA-CREW MESS-LAVANDERIA LOWER DECK
  { code: "BOR37", description: "COLLEGAMENTO APPARATI SENTINA ZONA CUCINA-CREW MESS-LAVANDERIA LOWER DECK", category: "BOR37" },

  // BOR38 - COLLEGAMENTO SENTINA ZONA CUCINA-CREW MESS-LAVANDERIA LOWER DECK
  { code: "BOR38", description: "COLLEGAMENTO SENTINA ZONA CUCINA-CREW MESS-LAVANDERIA LOWER DECK", category: "BOR38" },

  // BOR39 - INTESTAZIONE CAVI QUADRO ZONA MARINA LOWER DECK
  { code: "BOR3901", description: "INTESTAZIONE CAVI QUADRO ZONA MARINA LOWER DECK", category: "BOR39" },
  { code: "BOR3903", description: "COLLEGAMENTO QUADRO ZONA MARINA LOWER DECK", category: "BOR39" },

  // BOR40 - COLLEGAMENTO APPARATI MARINAI LOWER DECK
  { code: "BOR40", description: "COLLEGAMENTO APPARATI MARINAI LOWER DECK", category: "BOR40" },

  // BOR41 - COLLEGAMENTO SENTINA ZONA MARINAI DI PRUA
  { code: "BOR41", description: "COLLEGAMENTO SENTINA ZONA MARINAI DI PRUA", category: "BOR41" },

  // BOR42 - COLLEGAMENTO APPARATI LOCALE TECNICO PRUA
  { code: "BOR42", description: "COLLEGAMENTO APPARATI LOCALE TECNICO PRUA", category: "BOR42" },

  // BOR43 - INTESTAZIONE CAVI QUADRO MAIN DECK POPPA IN LOWER DECK
  { code: "BOR4301", description: "INTESTAZIONE CAVI QUADRO MAIN DECK POPPA IN LOWER DECK", category: "BOR43" },
  { code: "BOR4303", description: "COLLEGAMENTO QUADRO MAIN DECK POPPA IN LOWER DECK", category: "BOR43" },

  // BOR44 - INTESTAZIONE CAVI QUADRO PONTE MAIN DECK
  { code: "BOR4401", description: "INTESTAZIONE CAVI QUADRO PONTE MAIN DECK", category: "BOR44" },
  { code: "BOR4403", description: "COLLEGAMENTO QUADRO PONTE MAIN DECK", category: "BOR44" },

  // BOR45 - COLLEGAMENTO APPARATI VIP CENTRO E ARMATORE MAIN DECK
  { code: "BOR45", description: "COLLEGAMENTO APPARATI VIP CENTRO E ARMATORE MAIN DECK", category: "BOR45" },

  // BOR46 - COLLEGAMENTO APPARATI VIP POPPA MAIN DECK
  { code: "BOR46", description: "COLLEGAMENTO APPARATI VIP POPPA MAIN DECK", category: "BOR46" },

  // BOR47 - INTESTAZIONE CAVI QUADRO PONTE UPPER DECK
  { code: "BOR4701", description: "INTESTAZIONE CAVI QUADRO PONTE UPPER DECK", category: "BOR47" },
  { code: "BOR4703", description: "COLLEGAMENTO QUADRO PONTE UPPER DECK", category: "BOR47" },

  // BOR48 - COLLEGAMENTO APPARATI SALONE E SALA DA PRANZO UPPER DECK
  { code: "BOR48", description: "COLLEGAMENTO APPARATI SALONE E SALA DA PRANZO UPPER DECK", category: "BOR48" },

  // BOR49 - INTESTAZIONE CAVI QUADRO VALVOLE SENTINA
  { code: "BOR4901", description: "INTESTAZIONE CAVI QUADRO VALVOLE SENTINA", category: "BOR49" },
  { code: "BOR4903", description: "COLLEGAMENTO QUADRO VALVOLE SENTINA", category: "BOR49" },

  // BOR50 - COLLEGAMENTO QUADRO UPS
  { code: "BOR5002", description: "COLLEGAMENTO QUADRO UPS", category: "BOR50" },

  // BOR51 - COLLEGAMENTO QUADRO ALIMENTATORI UPPER DECK
  { code: "BOR51", description: "COLLEGAMENTO QUADRO ALIMENTATORI UPPER DECK", category: "BOR51" },

  // BOR52 - INTESTAZIONE CAVI QUADRO LUCI ESTERNE E ALIMENTATORI BRIDGE DECK
  { code: "BOR5201", description: "INTESTAZIONE CAVI QUADRO LUCI ESTERNE E ALIMENTATORI BRIDGE DECK", category: "BOR52" },
  { code: "BOR5203", description: "COLLEGAMENTO QUADRO LUCI ESTERNE E ALIMENTATORI BRIDGE DECK", category: "BOR52" },

  // BOR53 - COLLEGAMENTO APPARATI CABINA CAPITANO BRIDGE DECK
  { code: "BOR53", description: "COLLEGAMENTO APPARATI CABINA CAPITANO BRIDGE DECK", category: "BOR53" },

  // BOR54 - INTESTAZIONE CAVI QUADRO TIMONERIA BRIDGE DECK
  { code: "BOR5401", description: "INTESTAZIONE CAVI QUADRO TIMONERIA BRIDGE DECK", category: "BOR54" },
  { code: "BOR5403", description: "COLLEGAMENTO QUADRO TIMONERIA BRIDGE DECK", category: "BOR54" },

  // BOR55 - COLLEGAMENTO APPARATI TIMONERIA - CRUSCOTTO ALETTE
  { code: "BOR55", description: "COLLEGAMENTO APPARATI TIMONERIA - CRUSCOTTO ALETTE", category: "BOR55" },

  // BOR56 - COLLEGAMENTO APPARATI ESTERNI GARAGE-UPPER DECK-BRIDGE DECK
  { code: "BOR56", description: "COLLEGAMENTO APPARATI ESTERNI GARAGE-UPPER DECK-BRIDGE DECK", category: "BOR56" },

  // BOR57 - COLLEGAMENTO APPARATI SUN DECK-ALBERO
  { code: "BOR57", description: "COLLEGAMENTO APPARATI SUN DECK-ALBERO", category: "BOR57" },

  // BOR58 - COLLEGAMENTO QUADRO STACCABATTERIE RADIO-EMERGENZA
  { code: "BOR5803", description: "COLLEGAMENTO QUADRO STACCABATTERIE RADIO-EMERGENZA", category: "BOR58" },

  // BOR59 - COLLEGAMENTO APPARATI LOCALE TECNICO BRIDGE DECK (MATERIALE UPS E BATTERIE)
  { code: "BOR59", description: "COLLEGAMENTO APPARATI LOCALE TECNICO BRIDGE DECK (MATERIALE UPS E BATTERIE)", category: "BOR59" },

  // BOR60 - PROVE E COLLAUDI
  { code: "BOR60", description: "PROVE E COLLAUDI", category: "BOR60" },

  // BOR61 - INDENNITA' DI TRASFERTA
  { code: "BOR61", description: "INDENNITA' DI TRASFERTA", category: "BOR61" },
];

export const TIMESHEET_TYPES = {
  LAVORATO: "LAVORATO",
  MALATTIA: "MALATTIA",
  FERIE: "FERIE",
} as const;

export type TimesheetType = typeof TIMESHEET_TYPES[keyof typeof TIMESHEET_TYPES];
